import { createContext, useContext, useState } from "react";

const T = {
  pt: {
    allTime:"All-Time", settings:"Definições", darkMode:"Modo Escuro", lightMode:"Modo Claro",
    language:"Idioma", kills:"Abates", assists:"Assistências", timeLive:"Tempo Vivo",
    revives:"Revives", dmgDiff:"Dif. Dano", points:"Pontos", soloEvent:"Solo",
    teamsEvent:"Equipas", close:"Fechar", rank:"#", player:"Jogador", team:"Equipa",
    members:"Membros",
    footer:"The Last Survivor é um evento com mais de 10 streamers diferentes!",
    winner:"Vencedor", deaths:"Mortes", deathOrder:"Por Morte",
    howPointsWork:"Como funcionam os Pontos",
    timeLivePoints:"+1 pt por minuto vivo",
    casters:"Casters",
    tagFinal:"FINAL",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"INDISPONÍVEL",
    tagWinner:"VENCEDOR",
    tagEliminated:"ELIMINADO",
    tagGaveSlot:"CEDEU A VAGA NA FINAL",
    tagSecond:"2º LUGAR",
    tagThird:"3º LUGAR",
    tagFinalist:"FINALISTA",
    tagEliminatedGroupA:"ELIMINADO GRUPO A",
    tagEliminatedGroupB:"ELIMINADO GRUPO B",
    tagEliminatedGroupC:"ELIMINADO GRUPO C",
    days:"Dias",
    hours:"Horas",
    minutes:"Mins",
    seconds:"Segs",
    eventCountdown:"A começar em",
    manualPointsNote:"Nesta temporada os pontos foram definidos manualmente pelo organizador.",
    watchParty:"Watch Party",
    wpSub:"Vê o POV de todos os streamers da TLS III ao mesmo tempo.",
    wpAllPovs:"Todos os POVs",
    wpOpenChannel:"Abrir canal",
    wpNote:"Clica num POV para o pôr em grande e com som no leitor principal. As transmissões só aparecem quando os streamers estiverem ao vivo.",
    wpEmpty:"Ainda não há streamers definidos para esta temporada.",
    footerDisclaimer:"The Last Survivor não é afiliado, associado ou de qualquer forma ligado à Mojang Studios ou Microsoft Corporation. Minecraft® é uma marca registada da Mojang Synergies AB.",
    kofiSupportLine:"Buy The Last Survivor a Coffee",
    cahDescription:"Um servidor de Minecraft com Rankup, minas personalizadas, masmorras, chefes e uma comunidade ativa. Evolua, conquiste e faça parte de uma história que nunca terminou.",
    teamGreen:"Equipa Verde", teamBlue:"Equipa Azul", teamRed:"Equipa Vermelha", teamYellow:"Equipa Amarela",
    avatarsCredit:"Avatares de Minecraft fornecidos por", ranking:"Ranking", supporters:"Apoiantes",
    supportersSub:"Obrigado a quem apoia o The Last Survivor!", supportersEmpty:"Ainda não há apoiantes para mostrar.",
  },
  en: {
    allTime:"All-Time", settings:"Settings", darkMode:"Dark Mode", lightMode:"Light Mode",
    language:"Language", kills:"Kills", assists:"Assists", timeLive:"Living Time",
    revives:"Revives", dmgDiff:"Damage Dif.", points:"Points", soloEvent:"Solo",
    teamsEvent:"Teams", close:"Close", rank:"#", player:"Player", team:"Team",
    members:"Members",
    footer:"The Last Survivor is an event with more than 10 different streamers!",
    winner:"Winner", deaths:"Deaths", deathOrder:"By Death",
    howPointsWork:"How points work",
    timeLivePoints:"+1 pt per time alive minute",
    casters:"Casters",
    tagFinal:"FINAL",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"UNAVAILABLE",
    tagWinner:"WINNER",
    tagEliminated:"ELIMINATED",
    tagGaveSlot:"GAVE UP THE SPOT IN THE FINAL",
    tagSecond:"2ND PLACE",
    tagThird:"3RD PLACE",
    tagFinalist:"FINALISTS",
    tagEliminatedGroupA:"GROUP A ELIMINATED",
    tagEliminatedGroupB:"GROUP B ELIMINATED",
    tagEliminatedGroupC:"GROUP C ELIMINATED",
    days:"Days",
    hours:"Hours",
    minutes:"Mins",
    seconds:"Secs",
    eventCountdown:"Starting in",
    manualPointsNote:"At that time, the points were set manually by the organizer.",
    watchParty:"Watch Party",
    wpSub:"See the POV of all TLS III streamers at the same time.",
    wpAllPovs:"All POVs",
    wpOpenChannel:"Open channel",
    wpNote:"Click on a POV to make it bigger and with sound in the main player. The streams only show up when the streamers are live.",
    wpEmpty:"There aren't any streamers set for this season yet.",
    footerDisclaimer:"The Last Survivor is not affiliated, associated, or in any way connected to Mojang Studios or Microsoft Corporation. MinecraftÂ® is a registered trademark of Mojang Synergies AB.",
    kofiSupportLine:"Buy The Last Survivor a Coffee",
    cahDescription:"A Minecraft server with Rankup, custom mines, dungeons, bosses, and an active community. Level up, conquer, and be part of a story that never ends.",
    teamGreen:"Green Team", teamBlue:"Blue Team", teamRed:"Red Team", teamYellow:"Yellow Team",
    avatarsCredit:"Minecraft avatars provided by", ranking:"Ranking", supporters:"Supporters",
    supportersSub:"Thanks to everyone who supports The Last Survivor!", supportersEmpty:"There aren't any supporters yet.",
  },
  es: {
    allTime:"All-Time", settings:"Definiciones", darkMode:"Modo Oscuro", lightMode:"Modo Claro",
    language:"Idioma", kills:"Abates", assists:"Asistencias", timeLive:"Minuto En Vivo",
    revives:"Revives", dmgDiff:"Dif. Daño", points:"Puntos", soloEvent:"Solo",
    teamsEvent:"Equipos", close:"Cerrar", rank:"#", player:"Jugador", team:"Equipo",
    members:"Miembros",
    footer:"¡The Last Survivor es un evento con más de 10 streamers diferentes!",
    winner:"Vencedor", deaths:"Muertes", deathOrder:"Por Muerte",
    howPointsWork:"Cómo funcionan los Puntos",
    timeLivePoints:"+1 pt por minuto en vivo",
    casters:"Presentadores",
    tagFinal:"FINAL",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"NO DISPONIBLE",
    tagWinner:"VENCEDOR",
    tagEliminated:"ELIMINADO",
    tagGaveSlot:"CEDIÓ EL LUGAR EN LA FINAL",
    tagSecond:"2º LUGAR",
    tagThird:"3º LUGAR",
    tagFinalist:"FINALISTA",
    tagEliminatedGroupA:"ELIMINADO GRUPO A",
    tagEliminatedGroupB:"ELIMINADO GRUPO B",
    tagEliminatedGroupC:"ELIMINADO GRUPO C",
    days:"Días",
    hours:"Horas",
    minutes:"Mins",
    seconds:"Segs",
    eventCountdown:"A empezar en",
    manualPointsNote:"En esta época, los puntos eran definidos manualmente por el organizador.",
    watchParty:"Watch Party",
    wpSub:"Ve el POV de todos los streamers de la TLS III al mismo tiempo.",
    wpAllPovs:"Todos los POVs",
    wpOpenChannel:"Abrir canal",
    wpNote:"Haz clic en un POV para ponerlo en grande y con sonido en el reproductor principal. Las transmisiones solo aparecen cuando los streamers estén en vivo.",
    wpEmpty:"Todavía no hay streamers definidos para esta temporada.",
    footerDisclaimer:"The Last Survivor no está afiliado, asociado ni de ninguna forma relacionado con Mojang Studios o Microsoft Corporation. Minecraft® es una marca registrada de Mojang Synergies AB.",
    kofiSupportLine:"Compra un café para The Last Survivor",
    cahDescription:"Un servidor de Minecraft con Rankup, minas personalizadas, mazmorras, jefes y una comunidad activa. Evoluciona, conquista y forma parte de una historia que nunca terminó.",
    teamGreen:"Equipo Verde", teamBlue:"Equipo Azul", teamRed:"Equipo Rojo", teamYellow:"Equipo Amarillo",
    avatarsCredit:"Avatares de Minecraft proporcionados por", ranking:"Ranking", supporters:"Seguidores",
    supportersSub:"¡Gracias a quien apoya The Last Survivor!", supportersEmpty:"Aún no hay seguidores para mostrar.",
  },
};

const Ctx = createContext();
export function LangProvider({ children }) {
  const [lang, setLang] = useState("pt");
  return (
    <Ctx.Provider value={{ lang, setLang, t: k => T[lang][k] ?? T.en[k] ?? k }}>
      {children}
    </Ctx.Provider>
  );
}
export const useLang = () => useContext(Ctx);
