import { createContext, useContext, useState } from "react";

const T = {
  pt: {
    allTime:"All-Time", settings:"Definições", darkMode:"Modo Escuro", lightMode:"Modo Claro",
    language:"Idioma", kills:"Abates", assists:"Assistências", timeLive:"Tempo Vivo",
    revives:"Revives", dmgDiff:"Dif. Dano", points:"Pontos", soloEvent:"Solo",
    teamsEvent:"Equipas", close:"Fechar", rank:"#", player:"Jogador", team:"Equipa",
    members:"Membros",
    footer:"The Last Survivor é um evento com mais de 10 streamers diferentes!",
    winner:"Vencedor", deaths:"Mortes", deathOrder:"Por Morte",
    howPointsWork:"Como funcionam os Pontos",
    timeLivePoints:"+1 pt por minuto vivo",
    casters:"Casters",
    tagFinal:"FINAL",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"INDISPONÍVEL",
    tagWinner:"VENCEDOR",
    tagEliminated:"ELIMINADO",
    tagGaveSlot:"CEDEU A VAGA NA FINAL",
    tagSecond:"2º LUGAR",
    tagThird:"3º LUGAR",
    tagFinalist:"FINALISTA",
    tagEliminatedGroupA:"ELIMINADO GRUPO A",
    tagEliminatedGroupB:"ELIMINADO GRUPO B",
    tagEliminatedGroupC:"ELIMINADO GRUPO C",
    days:"Dias",
    hours:"Horas",
    minutes:"Mins",
    seconds:"Segs",
    eventCountdown:"A começar em",
    manualPointsNote:"Nesta época os pontos foram definidos manualmente pelo organizador.",
    watchParty:"Watch Party",
    wpSub:"Vê o POV de todos os streamers da TLS III ao mesmo tempo.",
    wpAllPovs:"Todos os POVs",
    wpOpenChannel:"Abrir canal",
    wpNote:"Clica num POV para o pôr em grande e com som no leitor principal. As transmissões só aparecem quando os streamers estiverem ao vivo.",
    wpEmpty:"Ainda não há streamers definidos para esta época.",
    footerDisclaimer:"The Last Survivor não é afiliado, associado ou de qualquer forma ligado à Mojang Studios ou Microsoft Corporation. Minecraft® é uma marca registada da Mojang Synergies AB.",
    kofiSupportLine:"Buy The Last Survivor a Coffee",
    cahDescription:"Um servidor de Minecraft com Rankup, minas personalizadas, masmorras, chefes e uma comunidade ativa. Evolua, conquiste e faça parte de uma história que nunca terminou.",
    teamGreen:"Equipa Verde", teamBlue:"Equipa Azul", teamRed:"Equipa Vermelha", teamYellow:"Equipa Amarela",
    mcHeadsCredit:"Cabeças dos jogadores fornecidas pela API Minecraft Heads.",
    design:"Design", designClassic:"Clássico", designMcc:"Moderno",
  },
  en: {
    allTime:"All-Time", settings:"Settings", darkMode:"Dark Mode", lightMode:"Light Mode",
    language:"Language", kills:"Kills", assists:"Assists", timeLive:"Time Alive",
    revives:"Revives", dmgDiff:"Dmg Diff", points:"Points", soloEvent:"Solo",
    teamsEvent:"Teams", close:"Close", rank:"#", player:"Player", team:"Team",
    members:"Members",
    footer:"The Last Survivor is an event featuring more than 10 different streamers!",
    winner:"Winner", deaths:"Deaths", deathOrder:"By Death",
    howPointsWork:"How Points Work",
    timeLivePoints:"+1 pt for every minute alive",
    casters:"Casters",
    tagFinal:"FINAL",
    tagSecond:"2nd PLACE",
    tagThird:"3rd PLACE",
    tagFinalist:"FINALIST",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"UNAVAILABLE",
    tagWinner:"WINNER",
    tagEliminated:"ELIMINATED",
    tagGaveSlot:"GAVE UP A FINAL SPOT",
    tagEliminatedGroupA:"ELIMINATED · GROUP A",
    tagEliminatedGroupB:"ELIMINATED · GROUP B",
    tagEliminatedGroupC:"ELIMINATED · GROUP C",
    days:"Days",
    hours:"Hours",
    minutes:"Mins",
    seconds:"Secs",
    eventCountdown:"Starts in",
    manualPointsNote:"Points for this season were set manually by the organizer.",
    watchParty:"Watch Party",
    wpSub:"Watch every TLS III streamer's POV at once.",
    wpAllPovs:"All POVs",
    wpOpenChannel:"Open channel",
    wpNote:"Click any POV to bring it into the main player with sound. Streams only show up once the streamers go live.",
    wpEmpty:"No streamers have been added for this season yet.",
    footerDisclaimer:"The Last Survivor is not affiliated with, associated with, or in any way connected to Mojang Studios or Microsoft Corporation. Minecraft® is a trademark of Mojang Synergies AB.",
    kofiSupportLine:"Buy The Last Survivor a coffee",
    cahDescription:"A Minecraft server with Rankup, custom mines, dungeons, bosses, and an active community. Level up, conquer, and become part of a story that never truly ended.",
    teamGreen:"Green Team", teamBlue:"Blue Team", teamRed:"Red Team", teamYellow:"Yellow Team",
    mcHeadsCredit:"Player heads provided by the Minecraft Heads API.",
    design:"Design", designClassic:"Classic", designMcc:"Modern",
  },
  es: {
    allTime:"Histórico", settings:"Ajustes", darkMode:"Modo Oscuro", lightMode:"Modo Claro",
    language:"Idioma", kills:"Bajas", assists:"Asistencias", timeLive:"Tiempo Vivo",
    revives:"Reanimaciones", dmgDiff:"Dif. Daño", points:"Puntos", soloEvent:"Individual",
    teamsEvent:"Equipos", close:"Cerrar", rank:"#", player:"Jugador", team:"Equipo",
    members:"Miembros",
    footer:"¡The Last Survivor es un evento con más de 10 streamers diferentes!",
    winner:"Ganador", deaths:"Muertes", deathOrder:"Por Muerte",
    howPointsWork:"Cómo funcionan los puntos",
    timeLivePoints:"+1 pt por cada minuto con vida",
    casters:"Casters",
    tagFinal:"FINAL",
    tagSecond:"2.º PUESTO",
    tagThird:"3.er PUESTO",
    tagFinalist:"FINALISTA",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"NO DISPONIBLE",
    tagWinner:"GANADOR",
    tagEliminated:"ELIMINADO",
    tagGaveSlot:"CEDIÓ SU PLAZA EN LA FINAL",
    tagEliminatedGroupA:"ELIMINADO · GRUPO A",
    tagEliminatedGroupB:"ELIMINADO · GRUPO B",
    tagEliminatedGroupC:"ELIMINADO · GRUPO C",
    days:"Días",
    hours:"Horas",
    minutes:"Min",
    seconds:"Seg",
    eventCountdown:"Empieza en",
    manualPointsNote:"En esta temporada los puntos fueron asignados manualmente por el organizador.",
    watchParty:"Watch Party",
    wpSub:"Mira el POV de todos los streamers de TLS III a la vez.",
    wpAllPovs:"Todos los POVs",
    wpOpenChannel:"Abrir canal",
    wpNote:"Haz clic en un POV para verlo en grande y con sonido en el reproductor principal. Las transmisiones solo aparecen cuando los streamers están en directo.",
    wpEmpty:"Todavía no hay streamers definidos para esta temporada.",
    footerDisclaimer:"The Last Survivor no está afiliado, asociado ni conectado de ninguna forma con Mojang Studios o Microsoft Corporation. Minecraft® es una marca registrada de Mojang Synergies AB.",
    kofiSupportLine:"Invita un café a The Last Survivor",
    cahDescription:"Un servidor de Minecraft con Rankup, minas personalizadas, mazmorras, jefes y una comunidad activa. Sube de nivel, conquista y forma parte de una historia que nunca terminó.",
    teamGreen:"Equipo Verde", teamBlue:"Equipo Azul", teamRed:"Equipo Rojo", teamYellow:"Equipo Amarillo",
    mcHeadsCredit:"Cabezas de jugadores proporcionadas por la API de Minecraft Heads.",
    design:"Diseño", designClassic:"Clásico", designMcc:"Moderno",
  },
};

const Ctx = createContext();
export function LangProvider({ children }) {
  const [lang, setLang] = useState("pt");
  return (
    <Ctx.Provider value={{ lang, setLang, t: k => T[lang][k] ?? T.en[k] ?? k }}>
      {children}
    </Ctx.Provider>
  );
}
export const useLang = () => useContext(Ctx);
