import { createContext, useContext, useState } from "react";

const T = {
  pt: {
    allTime:"All-Time", settings:"Definições", darkMode:"Modo Escuro", lightMode:"Modo Claro",
    language:"Idioma", kills:"Abates", assists:"Assistências", timeLive:"Tempo Vivo",
    revives:"Revives", dmgDiff:"Dif. Dano", points:"Pontos", soloEvent:"Solo",
    teamsEvent:"Equipas", close:"Fechar", rank:"#", player:"Jogador", team:"Equipa",
    members:"Membros",
    footer:"The Last Survivor é um evento com mais de 10 streamers diferentes!",
    winner:"Vencedor", deaths:"Mortes", deathOrder:"Por Morte",
    howPointsWork:"Como funcionam os Pontos",
    timeLivePoints:"+1 pt por minuto vivo",
    casters:"Casters",
    tagFinal:"FINAL",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"INDISPONÍVEL",
    tagWinner:"VENCEDOR",
    tagEliminated:"ELIMINADO",
    tagGaveSlot:"CEDEU A VAGA NA FINAL",
    tagSecond:"2º LUGAR",
    tagThird:"3º LUGAR",
    tagFinalist:"FINALISTA",
    tagEliminatedGroupA:"ELIMINADO GRUPO A",
    tagEliminatedGroupB:"ELIMINADO GRUPO B",
    tagEliminatedGroupC:"ELIMINADO GRUPO C",
    days:"Dias",
    hours:"Horas",
    minutes:"Mins",
    seconds:"Segs",
    eventCountdown:"A começar em",
    manualPointsNote:"Nesta época os pontos foram definidos manualmente pelo organizador.",
    watchParty:"Watch Party",
    wpSub:"Vê o POV de todos os streamers da TLS III ao mesmo tempo.",
    wpAllPovs:"Todos os POVs",
    wpOpenChannel:"Abrir canal",
    wpNote:"Clica num POV para o ver em grande no leitor principal. As transmissões só aparecem quando os streamers estiverem ao vivo.",
    wpEmpty:"Ainda não há streamers definidos para esta época.",
    footerDisclaimer:"The Last Survivor não é afiliado, associado ou de qualquer forma ligado à Mojang Studios ou Microsoft Corporation. Minecraft® é uma marca registada da Mojang Synergies AB.",
    kofiSupportLine:"Buy The Last Survivor a Coffee",
    cahDescription:"Um servidor de Minecraft com Rankup, minas personalizadas, masmorras, chefes e uma comunidade ativa. Evolua, conquiste e faça parte de uma história que nunca terminou.",
  },
  en: {
    allTime:"All-Time", settings:"Settings", darkMode:"Dark Mode", lightMode:"Light Mode",
    language:"Language", kills:"Kills", assists:"Assists", timeLive:"Time Alive",
    revives:"Revives", dmgDiff:"Dmg Diff", points:"Points", soloEvent:"Solo",
    teamsEvent:"Teams", close:"Close", rank:"#", player:"Player", team:"Team",
    members:"Members",
    footer:"The Last Survivor is an event with over 10 different streamers!",
    winner:"Winner", deaths:"Deaths", deathOrder:"By Death",
    howPointsWork:"How Points Work",
    timeLivePoints:"+1 pt per minute alive",
    casters:"Casters",
    tagFinal:"FINAL",
    tagSecond:"2nd PLACE",
    tagThird:"3rd PLACE",
    tagFinalist:"FINALIST",
    tagPlayoff:"PLAY-OFF",
    tagAbsent:"UNAVAILABLE",
    tagWinner:"WINNER",
    tagEliminated:"ELIMINATED",
    tagGaveSlot:"GAVE UP A FINAL SPOT",
    tagEliminatedGroupA:"ELIMINATED GROUP A",
    tagEliminatedGroupB:"ELIMINATED GROUP B",
    tagEliminatedGroupC:"ELIMINATED GROUP C",
    days:"Days",
    hours:"Hours",
    minutes:"Mins",
    seconds:"Secs",
    eventCountdown:"Starting in",
    manualPointsNote:"Points in this season were manually set by the organizer.",
    watchParty:"Watch Party",
    wpSub:"Watch every TLS III streamer's POV at the same time.",
    wpAllPovs:"All POVs",
    wpOpenChannel:"Open channel",
    wpNote:"Click a POV to watch it large in the main player. Streams only appear when the streamers are live.",
    wpEmpty:"No streamers set for this season yet.",
    footerDisclaimer:"The Last Survivor is not affiliated, associated, or in any way connected to Mojang Studios or Microsoft Corporation. Minecraft® is a trademark of Mojang Synergies AB.",
    kofiSupportLine:"Buy The Last Survivor a Coffee",
    cahDescription:"A Minecraft server with Rankup, custom mines, dungeons, bosses, and an active community. Level up, conquer, and become part of a story that never ended.",
  },
};

const Ctx = createContext();
export function LangProvider({ children }) {
  const [lang, setLang] = useState("pt");
  return (
    <Ctx.Provider value={{ lang, setLang, t: k => T[lang][k] ?? k }}>
      {children}
    </Ctx.Provider>
  );
}
export const useLang = () => useContext(Ctx);