// Textos do site. Só português: o site deixou de ter seletor de idiomas.
// t("chave") devolve o texto; se a chave não existir, devolve a própria
// chave, para saltar à vista que falta.
const T = {
  allTime:"All-Time", settings:"Definições", darkMode:"Modo Escuro", lightMode:"Modo Claro",
  language:"Idioma", kills:"Abates", assists:"Assistências", timeLive:"Tempo Vivo",
  revives:"Revives", dmgDiff:"Dif. Dano", points:"Pontos", soloEvent:"Solo",
  teamsEvent:"Equipas", close:"Fechar", rank:"#", player:"Jogador", team:"Equipa",
  members:"Membros",
  footer:"The Last Survivor é um evento com mais de 10 streamers diferentes!",
  winner:"Vencedor", deaths:"Mortes", deathOrder:"Por Morte",
  howPointsWork:"Como funcionam os Pontos",
  timeLivePoints:"+1 pt por minuto vivo",
  casters:"Casters",
  tagFinal:"FINAL",
  tagPlayoff:"PLAY-OFF",
  tagAbsent:"INDISPONÍVEL",
  tagWinner:"VENCEDOR",
  tagEliminated:"ELIMINADO",
  tagGaveSlot:"CEDEU A VAGA NA FINAL",
  tagSecond:"2º LUGAR",
  tagThird:"3º LUGAR",
  tagFinalist:"FINALISTA",
  tagEliminatedGroupA:"ELIMINADO GRUPO A",
  tagEliminatedGroupB:"ELIMINADO GRUPO B",
  tagEliminatedGroupC:"ELIMINADO GRUPO C",
  days:"Dias",
  hours:"Horas",
  minutes:"Mins",
  seconds:"Segs",
  eventCountdown:"A começar em",
  manualPointsNote:"Nesta temporada os pontos foram definidos manualmente pelo organizador.",
  watchParty:"Watch Party",
  wpSub:"Vê o POV de todos os streamers da TLS III ao mesmo tempo.",
  wpAllPovs:"Todos os POVs",
  wpOpenChannel:"Abrir canal",
  wpNote:"Clica num POV para o pôr em grande e com som no leitor principal. As transmissões só aparecem quando os streamers estiverem ao vivo.",
  wpEmpty:"Ainda não há streamers definidos para esta temporada.",
  footerDisclaimer:"The Last Survivor não é afiliado, associado ou de qualquer forma ligado à Mojang Studios ou Microsoft Corporation. Minecraft® é uma marca registada da Mojang Synergies AB.",
  kofiSupportLine:"Buy The Last Survivor a Coffee",
  cahDescription:"Um servidor de Minecraft com Rankup, minas personalizadas, masmorras, chefes e uma comunidade ativa. Evolua, conquiste e faça parte de uma história que nunca terminou.",
  teamGreen:"Equipa Verde", teamBlue:"Equipa Azul", teamRed:"Equipa Vermelha", teamYellow:"Equipa Amarela",
  avatarsCredit:"Avatares de Minecraft fornecidos por", ranking:"Ranking", supporters:"Apoiantes",
  supportersSub:"Obrigado a quem apoia o The Last Survivor!", supportersEmpty:"Ainda não há apoiantes para mostrar.",
  champions:"Campeões", championsSub:"O pódio de cada edição do The Last Survivor.",
  championsEmpty:"Ainda não há pódios para mostrar.",
  draw:"Sorteio", drawSub:"Sorteia as equipas respeitando os níveis dos jogadores.",
  drawTeamSize:"Jogadores por equipa", drawNumTeams:"Nº de equipas", drawPlayers:"jogadores",
  drawStart:"Iniciar sorteio", drawNext:"Sortear próximo", drawRevealAll:"Revelar tudo",
  drawReset:"Recomeçar", drawFinished:"Sorteio completo", drawPool:"Jogadores (clica para excluir)",
  drawRemaining:"Ainda por sortear", drawTierSplit:"Divisão dos níveis",
  privacy:"Privacidade", drawToggle:"Sorteio de equipas", drawSource:"Ordenar por", drawSourceList:"Lista", drawSourceRanking:"Ranking Sazonal",
  drawRankingNote:"Os níveis seguem o Ranking Sazonal (pontos ÷ edições). Quem não tem edições jogadas conta como 0 e fica no Nível 1.",
  drawUnbalanced:"O número de jogadores tem de ser igual a jogadores por equipa × nº de equipas. Exclui ou inclui jogadores até bater certo.",
  drawImpossible:"Não há nenhuma combinação possível com estas regras. Tenta outro número de equipas ou inclui mais jogadores.",
  team_red:"Equipa Vermelha", team_blue:"Equipa Azul", team_green:"Equipa Verde", team_yellow:"Equipa Amarela",
  team_orange:"Equipa Laranja", team_purple:"Equipa Roxa", team_pink:"Equipa Rosa", team_grey:"Equipa Cinzenta",
  awards:"Prémios", records:"Recordes",
  highlightsSub:"Pódios, prémios e recordes de todas as edições do The Last Survivor.",
  recordsEmpty:"Ainda não há recordes para mostrar.", awardsSub:"Os prémios individuais de cada edição do The Last Survivor.",
  awardsEmpty:"Ainda não há prémios para mostrar.",
  awardMvp:"MVP", awardRevelation:"Jogador Revelação", awardFanFavourite:"Jogador Favorito dos Fãs",
  wiki:"Wiki", wikiSub:"Tudo o que precisas de saber sobre o The Last Survivor.",
  wikiEmpty:"Ainda não há artigos na wiki.",
  modeNormal:"Normal", modeComplex:"Sazonal", editions:"Edições", editionsShort:"ed.",
  modeComplexNote:"Sazonal: pontos divididos pelo número de edições que cada jogador disputou, para nivelar quem jogou mais épocas com quem jogou menos.",
};

export const t = (k) => T[k] ?? k;
